/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package com.dialog;

import com.model.FoundReport;
import javax.swing.ImageIcon;

/**
 *
 * @author Evan
 */
public class DetailBarang extends java.awt.Dialog {

    private FoundReport foundReport;
    
    public DetailBarang(java.awt.Frame parent, FoundReport foundReport) {
        super(parent, "Detail Barang", true); // true = modal
        this.foundReport = foundReport;
        initComponents();
        isiData();
        setLocationRelativeTo(parent);
    }
    
    private void isiData() {
        txtHeader.setText("Detail");
        
        String photoPath = foundReport.getPhotoPath();
        if (photoPath != null && !photoPath.isEmpty()) {
            ImageIcon icon = new ImageIcon(photoPath);
            java.awt.Image img = icon.getImage().getScaledInstance(250, 230, java.awt.Image.SCALE_SMOOTH);
            txtFoto.setIcon(new ImageIcon(img));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHeader = new javax.swing.JLabel();
        txtFoto = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        txtHeader.setText("jLabel1");

        txtFoto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHeader)
                    .addComponent(txtFoto))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFoto)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailBarang dialog = new DetailBarang(new java.awt.Frame(), null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtFoto;
    private javax.swing.JLabel txtHeader;
    // End of variables declaration//GEN-END:variables
}
