/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.frame.dashboard;

import com.dialog.DetailBarang;
import com.managers.ReportManager;
import com.model.FoundReport;
import com.model.LostReport;
import com.model.Report;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evan
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());

    private ReportManager reportManager;
    
    public DashboardAdmin(ReportManager reportManager) {
        initComponents();
        this.reportManager = reportManager;
        initFoundReport();
        initLostReport();
    }
    
    private void initFoundReport() {
        DefaultTableModel model = (DefaultTableModel) tblFound.getModel();
        model.setRowCount(0); // kosongkan dulu sebelum isi data

        ArrayList<Report> allReports = reportManager.getAllReports();
        int no = 1;
        for (Report r : allReports) {
            if (r instanceof FoundReport) {
                FoundReport f = (FoundReport) r;
                model.addRow(new Object[]{
                    no++,
                    f.getItem().getName(),
                    f.getStatus(),
                    f.getDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")),
                    f.getFoundLocation(),
                    "..."
                });
            }
        }
        
        tblFound.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int row = tblFound.rowAtPoint(e.getPoint());
                int col = tblFound.columnAtPoint(e.getPoint());
                int kolomDetail = tblFound.getColumnCount() - 1;

                if (col == kolomDetail && row >= 0) {
                int no = 1;
                    for (Report r : reportManager.getValidReports()) {
                        if (r instanceof FoundReport) {
                            if (no == (int) tblFound.getValueAt(row, 0)) {
                                DetailBarang dialog = new DetailBarang(DashboardAdmin.this, (FoundReport) r);
                                dialog.setVisible(true);
                                break;
                            }
                            no++;
                        }
                    }
                }
            }
        });
    }
    
        private void initLostReport() {
        DefaultTableModel model = (DefaultTableModel) tblLost.getModel();
        model.setRowCount(0); // kosongkan dulu sebelum isi data

        ArrayList<Report> allReports = reportManager.getAllReports();
        int no = 1;
        for (Report r : allReports) {
            if (r instanceof LostReport) {
                LostReport l = (LostReport) r;
                model.addRow(new Object[]{
                    no++,
                    l.getItem().getName(),
                    l.getStatus(),
                    l.getDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")),
                    l.getLostLocation(),
                    "..."
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFound = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLost = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Admin");

        tblFound.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblFound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Type", "Status", "Date", "Location", "Detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFound.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblFound);
        if (tblFound.getColumnModel().getColumnCount() > 0) {
            tblFound.getColumnModel().getColumn(0).setResizable(false);
            tblFound.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblFound.getColumnModel().getColumn(1).setResizable(false);
            tblFound.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblFound.getColumnModel().getColumn(2).setResizable(false);
            tblFound.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblFound.getColumnModel().getColumn(3).setResizable(false);
            tblFound.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblFound.getColumnModel().getColumn(4).setResizable(false);
            tblFound.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblFound.getColumnModel().getColumn(5).setResizable(false);
            tblFound.getColumnModel().getColumn(5).setPreferredWidth(2);
        }

        tblLost.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblLost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Type", "Status", "Date", "Location", "Detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLost);
        if (tblLost.getColumnModel().getColumnCount() > 0) {
            tblLost.getColumnModel().getColumn(0).setResizable(false);
            tblLost.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblLost.getColumnModel().getColumn(1).setResizable(false);
            tblLost.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblLost.getColumnModel().getColumn(2).setResizable(false);
            tblLost.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblLost.getColumnModel().getColumn(3).setResizable(false);
            tblLost.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblLost.getColumnModel().getColumn(4).setResizable(false);
            tblLost.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblLost.getColumnModel().getColumn(5).setResizable(false);
            tblLost.getColumnModel().getColumn(5).setPreferredWidth(2);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {ReportManager rm = new ReportManager(); new DashboardAdmin(rm).setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFound;
    private javax.swing.JTable tblLost;
    // End of variables declaration//GEN-END:variables
}
